#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

$n = 0
$sum = 0

while $n < 34
  $m = (((1 + Math.sqrt(5)) / 2)**$n/(Math.sqrt(5))).round
  if $m % 2 == 0
    $sum+=$m
    puts $m
  end
  $n+=1
end

puts $sum